apiVersion: v1
kind: Service
metadata:
  name: service-caddy-flux
  namespace: default
spec:
  type: NodePort  # Expose on node port
  selector:
    app: flux-caddy
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30116  # Fixed NodePort
