# clusters/k3s/flux-system/nginx-1-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-1-flux-Kustomization
  namespace: flux-system
spec:
  suspend: true
  interval: 5m
  path: ./clusters/k3s/apps/nginx-1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
