apiVersion: networking.k8s.io/v1
kind: Ingress
meta
  name: apache-http
  namespace: default
  annotations:
    # Explicitly use Traefik
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: apache.traefik.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: apache-http
            port:
              number: 8080

---
